const tableData = [
            { page: '14', author: '로베르 브레송', title: '당나귀 발타자르', year: '1966', genre: '영화'},
            { page: '44', author: '만 레이', title: '정지된 폭발', year: '1934', genre: '사진'},
            { page: '50', author: '찰스 레이', title: '혁명 반혁명', year: '1990', genre: '설치'},
            { page: '50', author: '마우리치오 카텔란', title: '스타디오', year: '1991', genre: '설치'},
            { page: '51', author: '한스페터 펠트만', title: '100년', year: '2001', genre: '사진'},

            { page: '51', author: '알리기에로 에 보에티', title: '아프가니스탄에서 온 720통의 편지', year: '1973', genre: '콜라주'},
            { page: '55', author: '렘브란트', title: '도살된 소', year: '1643', genre: '회화'},
            { page: '56', author: '프랑수아 트뤼포', title: '400번의 구타', year: '1959', genre: '영화'},
            { page: '59', author: '마르셀 브로타에스', title: '미술관의 독수리', year: '1625-27', genre: '회화'},
            { page: '59', author: '요제프 보이스', title: '사슴을 비추는 번개', year: '1958-85', genre: '설치'},
            
            { page: '59', author: '크리스티앙 볼탕스키', title: '가족 앨범', year: '1971', genre: '사진'},
            { page: '59', author: '레이몽 앵스', title: '벗겨진 포스터', year: '1961(?)', genre: '콜라주'},
            { page: '59', author: '미켈란젤로 피스톨레토', title: '거울', year: '1964', genre: '설치'},
            { page: '60', author: '프란시스코 리발타', title: '성 베르나르도를 감싸 안는 그리스도', year: '1625~27', genre: '회화'},
            { page: '62', author: '에두아르 마네', title: '천사들이 떠받친 죽은 그리스도', year: '1864', genre: '회화'},
            
            { page: '63', author: '알프레드 히치콕', title: '오명, 포마르 병', year: '1946', genre: '영화'},
            { page: '63', author: '알프레드 히치콕', title: '해외특파원, 풍차의 날개', year: '1940', genre: '영화'},
            { page: '63', author: '알프레드 히치콕', title: '마니, 핸드백', year: '1964', genre: '영화'},
            { page: '63', author: '알프레드 히치콕', title: '의혹, 우유잔', year: '1941', genre: '영화'},
            { page: '87', author: '아치 마요', title: '카사블랑카에서의 하룻밤[주석Ⅱ-19]', year: '1946', genre: '영화'},

            { page: '97', author: '로버트 시오드막', title: '나선 계단', year: '1946', genre: '영화'},
            { page: '99', author: '조르주 프랑주', title: '쥐덱스, 남성-새의 샷', year: '1963', genre: '영화'},
            { page: '99', author: '조르주 프랑주', title: '쥐덱스, 안토니오니의 눈 클로즈업', year: '1963', genre: '영화'},
            { page: '105', author: '크시슈토프 보디치코', title: '홈리스 프로젝션', year: '1986', genre: '설치'},
            { page: '106', author: '마사 로슬러', title: '붉은 줄무늬 주방', year: '1970', genre: '사진'},

            { page: '113', author: '장뤽 고다르', title: '미치광이 피에로[주석Ⅱ-31]', year: '1965', genre: '영화'},
            { page: '115', author: '디에고 벨라스케스', title: '라스 메니나스(시녀들)', year: '1656', genre: '회화'},
            { page: '117', author: '지오토 디 본도네', title: '막달라 마리아의 생애', year: '1320(?)', genre: '회화'},
            { page: '119', author: '바네사 비크로프트', title: 'BV46(동영상 출품작)', year: '2011', genre: '영상'},
            { page: '119', author: '리네커 딕스트라', title: 'De Panne(청소년 초상화)', year: '2011', genre: '사진'},
            
            { page: '120', author: '구겐하임 미술관', title: '전시소개[주석Ⅱ-36]', year: '2002', genre: '전시'},
            { page: '121', author: '그레고리 크루드슨', title: '무제: 위싱턴 거리', year: '2006', genre: '사진'},
            { page: '123', author: '빌 비올라', title: '앞으로 나아가기', year: '2002', genre: '영상'},
            { page: '124', author: '빌 비올라', title: '전시소개[주석Ⅱ-37]', year: '2002', genre: '전시'},
            { page: '125', author: '아레나 예배당', title: '지오토의 프레스코화', year: '1303', genre: '회화'},

            { page: '127', author: '켄 룸', title: 'Portrait-Repeated Text Series', year: '1993', genre: '사진'},
            { page: '127', author: '켄 룸', title: 'Midway Shopping Plaza', year: '2014', genre: '설치'},
            { page: '140', author: '장바티스트 그뢰즈', title: '셉티미우스 세베루스와 카라칼라', year: '1769', genre: '회화'},
            { page: '147', author: '페테르 루벤스', title: '십자가에서 내려지는 예수', year: '1800(?)', genre: '회화'},
            { page: '148', author: '카지미르 말레비치', title: '흰 바탕 위의 흰 사각형', year: '1918', genre: '회화'},
         
            { page: '151', author: '장바티스트시메옹 샤르댕', title: '정물화', year: '1900(?)', genre: '회화'},
            { page: '157', author: '폴 고갱', title: '설교가 끝난 후의 환상', year: '1888', genre: '회화'},
            { page: '182', author: '르네 마그리트', title: '대화술', year: '1950', genre: '회화'},
            { page: '193', author: '알렉산드르 로드첸코', title: '항공사 포스터', year: '1923', genre: '포스터'},
            { page: '193', author: '마르셀 뒤샹', title: '거대한 유리, 또는 독신 남자들이 발가벗긴 신부, 그조차도', year: '1915-23', genre: '설치'},
        ]

        const imageData = [
            { src : 'https://www.youtube.com/embed/fL7BVBnSErU',
            class : 'video', width : 854, height : 480 },
            { src : 'https://i.pinimg.com/originals/96/3a/47/963a474680b618c61f9d3d0f6d7e63df.jpg',
            class : 'image', width : "50%", height : "auto",  alt : 'http://aucieletsurlaterre.blogspot.com/2013/06/explosante-fixe.html' },
            { src : 'https://i.pinimg.com/originals/5c/48/57/5c48571c6cb585fa95856058b02f6ed6.jpg',
            class : 'image', width : "50%", height : "auto",  alt : 'https://i.pinimg.com/564x/5c/48/57/5c48571c6cb585fa95856058b02f6ed6.jpg' },
            { src : 'https://i.pinimg.com/originals/98/bb/b3/98bbb3857cb6ef193985fbb6b75d229d.jpg',
            class : 'image', width : "50%", height : "auto",  alt : 'http://www.flashartonline.it/article/un-artista-abusivo-sempre-presente/' },
            { src : 'https://i.pinimg.com/originals/43/7e/85/437e85e6c8209434547f5532c8289e34.jpg',
            class : 'image', width : "90%", height : "auto",  alt : 'https://www.flickr.com/사진s/thundershead/29895933835/in/사진stream/' },
            
            { src : 'https://i.pinimg.com/originals/f5/9f/75/f59f754506181b8c9e842435f0ebc2dc.png',
            class : 'image', width : "90%", height : "auto",  alt : 'https://morettigallery.com/usr/documents/exhibitions/list_of_works_url/39/catalogo_boetti.pdf' },
            { src : 'https://i.pinimg.com/originals/95/94/85/959485b792c46384c1d6c319eccb0547.jpg',
            class : 'image', width : "50%", height : "auto",  alt : 'https://theartstack.com/artist/rembrandt/slaughtered-ox-glasgow' },
            { src : 'https://www.youtube.com/embed/N9I-gsap0po',
            class : 'video', width : 854, height : 480 },
            { src : 'http://66.media.tumblr.com/tumblr_lzygfxMuh21r70t2xo1_1280.jpg',
            class : 'image', width : "90%", height : "auto",  alt : 'http://multitude.co.kr/361' },
            { src : 'https://images.guggenheim-bilbao.eus/src/uploads/2012/05/2002-Beuys-Rayo-iluminando-un-venado.jpg?_ga=2.265185676.2026058393.1546931770-693082786.1545986977',
            class : 'image', width : "90%", height : "auto",  alt : 'https://www.guggenheim-bilbao.eus/obras/rayo-iluminando-un-venado-2' },
            
            { src : 'https://i.pinimg.com/originals/e8/18/f4/e818f4592505a5aadf9c855ca5fff721.jpg',
            class : 'image', width : "90%", height : "auto",  alt : 'https://www.flickr.com/사진s/liminaire/39914008802' },
            { src : 'http://3.bp.blogspot.com/_5RQczaWDAY8/TC38JfWigXI/AAAAAAAACUM/PrjrQi32_B0/s400/Raymond+Hains1.jpg',
            class : 'image', width : "50%", height : "auto",  alt : 'http://teenagekittens.blogspot.com/2010/07/raymond-hains.html' },
            { src : 'http://www.sanjeev.net/modernart/man-with-yellow-pants-by-michelangelo-pistoletto-1161.jpg',
            class : 'image', width : "50%", height : "auto",  alt : 'http://www.sanjeev.net/modernart/man-with-yellow-pants-by-michelangelo-pistoletto-1161.html' },
            { src : 'https://content3.cdnprado.net/imagenes/Documentos/imgsem/f8/f878/f878e05f-b1b9-4cb0-b182-152e611bcec5/bd65106e-e0b0-4cd8-a3f3-831509037b49_832.jpg',
            class : 'image', width : "50%", height : "auto",  alt : 'https://www.museodelprado.es/en/the-collection/art-work/christ-embracing-saint-bernard/f878e05f-b1b9-4cb0-b182-152e611bcec5' },
            { src : 'https://upload.wikimedia.org/wikipedia/commons/e/eb/%C3%89douard_Manet_-_Le_Christ_mort_et_les_anges.jpg',
            class : 'image', width : "50%", height : "auto",  alt : 'https://fr.wikipedia.org/wiki/Fichier:%C3%89douard_Manet_-_Le_Christ_mort_et_les_anges.jpg' },
            
            { src : 'https://www.bfi.org.uk/sites/bfi.org.uk/files/styles/full/public/image/notorious-1946-014-cary-grant-ingrid-bergman-table-bottles-00n-zye.jpg?itok=tzx-GunM',
            class : 'image', width : "90%", height : "auto",  alt : 'https://www.bfi.org.uk/news-opinion/news-bfi/features/notorious-70th-anniversary' },
            { src : 'https://m.media-amazon.com/images/M/MV5BMzgwMzk2ZWYtZmU0OC00N2MyLWI2MGQtNzM1ZTdjMWMxOTJjXkEyXkFqcGdeQXVyNzc5NjM0NA@@._V1_.jpg',
            class : 'image', width : "50%", height : "auto",  alt : 'https://www.imdb.com/title/tt0032484/mediaindex?ref_=tt_pv_mi_sm' },
            { src : 'https://66.media.tumblr.com/tumblr_l11z96EC291qzdvhio1_r1_500.jpg',
            class : 'image', width : "50%", height : "auto",  alt : 'http://oldhollywood.tumblr.com/page/114' },
            { src : 'https://www.youtube.com/embed/Kk8FW9atXuw?start=20',
            class : 'video', width : 854, height : 480 },
            { src : 'https://www.youtube.com/embed/dCQCBmcPl2U',
            class : 'video', width : 854, height : 480 },

            { src : 'https://www.youtube.com/embed/kx9RQQldxa4?start=4485',
            class : 'video', width : 854, height : 480 },
            { src : 'https://i.kinja-img.com/gawker-media/image/upload/s--DVix59iE--/c_scale,f_auto,fl_progressive,q_80,w_800/qadvmujjzlscwgfom3r6.jpg',
            class : 'image', width : "90%", height : "auto",  alt : 'https://film.avclub.com/judex-new-to-criterion-packs-a-lot-of-lunacy-into-97-1798180729' },
            { src : 'https://www.eurekavideo.co.uk/sites/default/files/judex_19_300dpi.jpg',
            class : 'image', width : "90%", height : "auto",  alt : 'https://www.eurekavideo.co.uk/moc/judex' },
            { src : 'http://media.philstar.com/images/the-philippine-star/lifestyle/young-star/20180601/Ystyle2-Krzysztof-Wodiczko-The-Homeless-Projection.jpg',
            class : 'image', width : "50%", height : "auto",  alt : 'https://www.philstar.com/lifestyle/ystyle/2018/06/01/1820402/happening-today-artist-talk-krzysztof-wodiczko' },
            { src : 'https://www.metmuseum.org/toah/images/hb/hb_2002.393.jpg',
            class : 'image', width : "50%", height : "auto",  alt : 'https://www.metmuseum.org/toah/works-of-art/2002.393/' },
            
            { src : 'https://www.youtube.com/embed/OkV_qx2H2Go?start=74',
            class : 'video', width : 854, height : 480 },
            { src : 'https://i.pinimg.com/originals/b2/1e/50/b21e50e22b0a55a73607a47083ed8eca.jpg',
            class : 'image', width : "50%", height : "auto",  alt : 'https://www.museodelprado.es/en/the-collection/art-work/las-meninas/9fdc7800-9ade-48b0-ab8b-edee94ea877f' },
            { src : 'https://i.pinimg.com/originals/94/f0/00/94f000d2b8b29f228739b21d5ef52a80.jpg',
            class : 'image', width : "50%", height : "auto",  alt : 'https://i.pinimg.com/originals/94/f0/00/94f000d2b8b29f228739b21d5ef52a80.jpg' },
            { src : 'https://gagosian.com/media/images/exhibitions/2001/vanessa-beecroft-vb46/TejIKL0ZwC_f_2340x1316.jpg',
            class : 'image', width : "90%", height : "auto",  alt : 'https://gagosian.com/exhibitions/2001/vanessa-beecroft-vb46/' },
            { src : 'https://www.tate.org.uk/art/images/work/P/P78/P78328_10.jpg',
            class : 'image', width : "50%", height : "auto",  alt : 'https://www.tate.org.uk/art/artworks/dijkstra-de-panne-belgium-august-7-1992-p78328' },
            
            { src : 'https://i.pinimg.com/originals/c3/6a/5f/c36a5f7dbbff4d94bc6d3cd1c6017c72.png',
            class : 'image', width : "90%", height : "auto",  alt : 'http://pastexhibitions.guggenheim.org/moving_pictures/highlights_11d.html' },
            { src : 'https://i.pinimg.com/originals/31/fa/fa/31fafaa42b083fea2151418ee13cb9ba.jpg',
            class : 'image', width : "90%", height : "auto",  alt : 'http://www.americansuburbx.com/galleries/gregory-crewdson-beneath-the-roses' },
            { src : 'https://player.vimeo.com/video/13920661',
            class : 'video', width : 854, height : 480 },
            { src : 'https://i0.wp.com/www.guggenheim.org/wp-content/uploads/2007/12/installation-deutsche-berlin-viola-e1459886158189.jpg?w=870&zoom=2',
            class : 'image', width : "90%", height : "auto",  alt : 'https://www.guggenheim.org/exhibition/bill-viola-going-forth-by-day' },
            { src : 'https://cdn2.iguzzini.com/getmedia/f5424586-4cf7-4cc1-86c8-8462c4c68baa/Cappella_degli_Scrovegni_01?',
            class : 'image', width : "90%", height : "auto",  alt : 'https://www.iguzzini.com/projects/project-gallery/the-scrovegni-chapel/' },
            
            { src : 'http://kenlumart.com/wp-content/uploads/1993/07/MG_3709.jpg',
            class : 'image', width : "90%", height : "auto",  alt : 'http://kenlumart.com/untitled-collection/' },
            { src : 'http://kenlumart.com/wp-content/uploads/2017/07/80-MidwayPlaza.jpg',
            class : 'image', width : "50%", height : "auto",  alt : 'http://kenlumart.com/signage/' },
            { src : 'https://upload.wikimedia.org/wikipedia/commons/8/86/Jean-Baptiste_Greuze_-_Septimius_Severus_and_Caracalla_-_WGA10673.jpg',
            class : 'image', width : "70%", height : "auto",  alt : 'https://commons.wikimedia.org/wiki/File:Jean-Baptiste_Greuze_-_Septimius_Severus_and_Caracalla_-_WGA10673.jpg' },
            { src : 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/96/La_descente_de_croix_Rubens.jpg/520px-La_descente_de_croix_Rubens.jpg',
            class : 'image', width : "50%", height : "auto",  alt : 'https://fr.wikipedia.org/wiki/Descente_de_croix_(Rubens)' },
            { src : 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4c/White_on_White_%28Malevich%2C_1918%29.png/520px-White_on_White_%28Malevich%2C_1918%29.png',
            class : 'image', width : "50%", height : "auto",  alt : 'https://fr.wikipedia.org/wiki/Carr%C3%A9_blanc_sur_fond_blanc' },
           
            { src : 'https://www.art-prints-on-demand.com/kunst/jean_baptiste_simeon_chardin/chardin_white_teaspot.jpg',
            class : 'image', width : "50%", height : "auto",  alt : 'http://www.artnet.com/artists/jean-baptiste-sim%C3%A9on-chardin/5' },
            { src : 'https://www.nationalgalleries.org/sites/default/files/styles/feature_header/public/externals/11695.jpg?itok=kxHIqBOV',
            class : 'image', width : "50%", height : "auto",  alt : 'https://www.nationalgalleries.org/art-and-artists/4940/vision-sermon-jacob-wrestling-angel' },
            { src : 'https://i.pinimg.com/originals/18/8a/35/188a35275cd7276d92c0190351bf911e.jpg',
            class : 'image', width : "90%", height : "auto",  alt : 'https://i.pinimg.com/originals/18/8a/35/188a35275cd7276d92c0190351bf911e.jpg' },
            { src : 'https://www.moma.org/media/W1siZiIsIjIxMTU1MyJdLFsicCIsImNvbnZlcnQiLCItcmVzaXplIDIwMDB4MjAwMFx1MDAzZSJdXQ.jpg?sha=2a20771e14f63561',
            class : 'image', width : "90%", height : "auto",  alt : 'https://www.moma.org/collection/works/7269' },
            { src : 'https://www.tate.org.uk/art/images/work/T/T02/T02011_10.jpg',
            class : 'image', width : "50%", height : "auto",  alt : 'https://www.tate.org.uk/art/artworks/duchamp-the-bride-stripped-bare-by-her-bachelors-even-the-large-glass-t02011' },
        ]